version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    env_file:
      - .env
    volumes:
      - ./mc-data:/data
      - ./whitelist.json:/data/whitelist.json
  backups:
    image: itzg/mc-backup
    user: "1000"
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      # As an example, to backup only the world data:
      # INCLUDES: world,world_nether,world_the_end
    volumes:
      - ./mc-data:/data:ro
      - ./mc-backups:/backups
    healthcheck:
      test: mc-health
      start_period: 4m
      interval: 15s
      retries: 20
    #restore-backup:
    # Same image as mc, but any base image with bash and tar will work
    #  image: itzg/mc-backup
    #  user: "1000"
    #  restart: no
    #  entrypoint: restore-tar-backup
    #  volumes:
        # Must be same mount as mc service, needs to be writable
    #    - ./mc-data:/data
        # Must be same mount as backups service, but can be read-only
    #    - ./mc-backups:/backups:ro
  